# SESSION ------------------------------------------------

library(shiny)
library(shinythemes)
library(jsonlite)
library(httr)
library(RCurl)
library(tidyverse)

#consumer key + consumer secret
# Your consumer key and consumer secret generated by discogs when an application is created
# and registered . See http://www.discogs.com/settings/developers . These credentials
# are assigned by application and remain static for the lifetime of your discogs application.
consumer_key <- "BEKNNZckQTZGTkinGrSE"
consumer_secret <-"CeJArzdbkbYRuRiJETWtTWEqXDdqLTZC"

#create unique user agent id
user_agent <-  'DiscogsViz/1.0'

#set URL parameters for querying collections
baseURL <- 'https://api.discogs.com//users/'
tailURL <- '/collection/folders/0/releases'


# COLLECTION RETRIEVAL FUNCTION -------------------------------------------

#function for querying and building tidy user's collection
getCollection <- function(username){
  
  #call API to retrieve raw users collection
  baseURL <- 'https://api.discogs.com//users/'
  tailURL <- '/collection/folders/0/releases'
  pre_run <- getURL(paste0(baseURL, username, tailURL),
                    httpheader=c('User-Agent'=user_agent))
  pre_run <- fromJSON(pre_run)
  
  #loop through collection pages and bind to dataframe
  pages <- list()
  for(i in 1:pre_run$pagination$pages){
    mydata <- fromJSON(paste0(baseURL, username,
                              tailURL, "?page=", i), flatten=TRUE)
    message("Retrieving page ", i)
    pages[[i+1]] <- mydata$releases
  }
  data <- rbind.pages(pages)
  data <- as.data.table(data)
  data <- data[!duplicated(data), ]
  
  #flatten and clean label info
  labels <- unnest(data, basic_information.labels)
  valid_column_names <- make.names(names=names(labels), unique=TRUE, allow_ = TRUE)
  names(labels) <- valid_column_names
  
  labels <- labels %>%
    select(instance_id, name, catno, resource_url)  %>%
    rename(label_name = name, label_url = resource_url) %>%
    filter(!duplicated(instance_id))
  
  #flatten and clean format info
  formats <- unnest(data, basic_information.formats) %>%
    select(instance_id, descriptions:text) %>%
    rename(format_name=name, format_text=text) %>%
    unnest(descriptions) %>%
    spread(key=descriptions, value=descriptions) %>%
    filter(!duplicated(instance_id))
  
  #flatten and clean artist info
  artists <- unnest(data, basic_information.artists)
  valid_column_names <- make.names(names=names(artists), unique=TRUE, allow_ = TRUE)
  names(artists) <- valid_column_names
  
  artists <- artists %>%
    select(instance_id, name, basic_information.title, resource_url) %>%
    rename(artist_name=name, artist_url=resource_url) %>%
    filter(!duplicated(instance_id))
  
  #bind this all together (apart from formats, they need a separate join)
  data <- select(data, instance_id:rating, basic_information.year)
  data <- cbind(data, artists, labels, id="instance_id")
  
  #make col names unique
  valid_column_names <- make.names(names=names(data), unique=TRUE, allow_ = TRUE)
  names(data) <- valid_column_names
  
  #remove unneeded cols
  data <- select(data, -rating, -instance_id.1, -instance_id.2, -id.1)
  
  data <- left_join(data, formats, by = c("instance_id"="instance_id"))
}


# UI --------------------------------------------------------------

# Define UI for application that draws a histogram
ui <- navbarPage("Vinylspotting",
                 theme = shinytheme("cosmo"),
   
   # Application title
   tabPanel("App",
   # bit with the username input and submit button 
   fluidRow(
     
     column(3,
      wellPanel(
        textInput("username", label="Username", value = "", width = NULL, placeholder = "Enter your Discogs username"),
        actionButton("go", "Submit")),
    # bit with the years slider and x-axis var selector
      wellPanel(
        sliderInput("year", "Your digging years", min=1940, max=as.integer(format(Sys.Date(), "%Y")),
                    value = c(1940, as.integer(format(Sys.Date(), "%Y")))),
        selectInput("xvar", "Wot 2 plot?", c("Labels", "Artists"), selected = "label_name")
)),
  # Main panel w/ plot
    column(9,  
      wellPanel(
        highchartOutput("plot", height = "500px")
      ))
   )
),
  # about page (draws from Rmd file)
  tabPanel("About",
         fluidRow(
           column(6,
                  includeMarkdown("About.Rmd")
           ))))


# SERVER -------------------------------------------------------------

server <- function(input, output, session) {
  
  # reactivevent - retrieve user collection when action button pressed
  data <- eventReactive(input$go, {
    withProgress(message = 'Hold tight...',
                 value = 0, {
                   for (i in 1:15) {
                     incProgress(1/15)
                   }
                   getCollection(input$username)
                 })
  })
  
  # filter collection based on session inputs
  data_filtered <- reactive({
    minyear <- input$year[1]
    maxyear <- input$year[2]
    df <- data() %>%
      filter(year(date_added) >= minyear,
             year(date_added) <= maxyear)
    df <- as.data.frame(df)
  })
  
  # observer - update available slider values based on years present in users collection
  observe({
    minyear <- min(year(data()$date_added))
    maxyear <- max(year(data()$date_added))
    # Control the value, min, max, and step.
    # Step size is 2 when input value is even; 1 when value is odd.
    updateSliderInput(session, "year",
                      min = minyear,
                      max = maxyear,
                      value= c(minyear, maxyear))
  })
  
  # highchart output dependent on x-axis var picked by user 
  output$plot <- renderHighchart({
    
    if (input$xvar == "Labels") {
      data_filtered() %>%
      group_by(label_name) %>%
      summarise(Records = n()) %>%
      arrange(desc(Records)) %>%
      top_n(10) %>%
      hchart("column", hcaes(x = label_name, y = Records), name="Records") %>%
      hc_xAxis(title = list(text = "Labels")) 
    }
    else if (input$xvar == "Artists") {
      data_filtered() %>%
        group_by(artist_name) %>%
        summarise(Records = n()) %>%
        arrange(desc(Records)) %>%
        filter(artist_name != "Various") %>%
        top_n(10) %>%
        hchart("column", hcaes(x = artist_name, y = Records), name="Records") %>%
        hc_xAxis(title = list(text = "Artists")) 
    }
  })
}

# Run the application 
shinyApp(ui = ui, server = server)

