---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
###### SESSION ######

library(jsonlite)
library(httr)
library(RCurl)
library(tidyverse)
library(data.table)
library(highcharter)
library(lubridate)
require(zoo)

#consumer key + consumer secret
# Your consumer key and consumer secret generated by discogs when an application is created
# and registered . See http://www.discogs.com/settings/developers . These credentials
# are assigned by application and remain static for the lifetime of your discogs application.
consumer_key <- "BEKNNZckQTZGTkinGrSE"
consumer_secret <-"CeJArzdbkbYRuRiJETWtTWEqXDdqLTZC"

# #oauth end-points  
# # The following oauth end-points are defined by discogs.com staff. These static endpoints
# # are called at various stages of oauth handshaking.
# Request_Token_URL	<- "https://api.discogs.com/oauth/request_token"
# Authorize_URL	<- "https://www.discogs.com/oauth/authorize"
# Access_Token_URL <- "https://api.discogs.com/oauth/access_token"

#create unique user agent id
user_agent <-  'DiscogsViz/1.0'
```


# Get collection function

```{r}
getCollection <- function(username){
  
  #call API to retrieve raw users collection
  baseURL <- 'https://api.discogs.com//users/'
  tailURL <- '/collection/folders/0/releases'
  pre_run <- getURL(paste0(baseURL, username, tailURL),
                    httpheader=c('User-Agent'=user_agent))
  pre_run <- fromJSON(pre_run)
  
  #loop through collection pages and bind to dataframe
  pages <- list()
  for(i in 1:pre_run$pagination$pages){
    mydata <- fromJSON(paste0(baseURL, username,
                              tailURL, "?page=", i), flatten=TRUE)
    message("Retrieving page ", i)
    pages[[i+1]] <- mydata$releases
  }
  data <- rbind.pages(pages)
  data <- as.data.table(data)
  data <- data[!duplicated(data), ]

  #flatten and clean label info
  labels <- unnest(data, basic_information.labels)
  valid_column_names <- make.names(names=names(labels), unique=TRUE, allow_ = TRUE)
  names(labels) <- valid_column_names

  labels <- labels %>%
    select(instance_id, name, catno, resource_url)  %>%
    rename(label_name = name, label_url = resource_url) %>%
    filter(!duplicated(instance_id))

  #flatten and clean format info
  formats <- unnest(data, basic_information.formats) %>%
    select(instance_id, descriptions:text) %>%
    rename(format_name=name, format_text=text) %>%
    unnest(descriptions)
  
  formats <- formats[!duplicated(formats), ]
  
  formats <- formats %>%
    spread(key=descriptions, value=descriptions) %>%
    filter(!duplicated(instance_id))

  #flatten and clean artist info
  artists <- unnest(data, basic_information.artists)
  valid_column_names <- make.names(names=names(artists), unique=TRUE, allow_ = TRUE)
  names(artists) <- valid_column_names

  artists <- artists %>%
    select(instance_id, name, basic_information.title, resource_url) %>%
    rename(artist_name=name, artist_url=resource_url) %>%
    filter(!duplicated(instance_id))

  #bind it all together
  data <- select(data, instance_id:rating, basic_information.year)
  data <- cbind(data, artists, labels, id="instance_id")

  #make col names unique
  valid_column_names <- make.names(names=names(data), unique=TRUE, allow_ = TRUE)
  names(data) <- valid_column_names

  #remove unneeded cols
  data <- select(data, -rating, -instance_id.1, -instance_id.2)

  data <- left_join(data, formats, by = c("instance_id"="instance_id"))
}

data <- getCollection('bakes09081466')

```


### Breakdown

```{r}
# top labels
test %>%
  group_by(label_name) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  top_n(10) %>%
  hchart("column", hcaes(x = label_name, y = count), name="Records")

# top artists
test %>%
  group_by(artist_name) %>%
  summarise(count = n()) %>%
  filter(artist_name != "Various") %>%
  arrange(desc(count)) %>%
  top_n(10) %>%
  hchart("column", hcaes(x = artist_name, y = count), name="Records")

# vinyl formats
test %>%
  summarise(`12"` = sum(`12"` == "12\"", na.rm=TRUE),
            `10"` = sum(`10"` == "10\"", na.rm=TRUE),
            `7"` = sum(`7"` == "7\"", na.rm=TRUE),
            LP = sum(LP == "LP", na.rm=TRUE),
            CD = sum(format_name == "CD", na.rm=TRUE)) %>%
  gather(key=`Format`, value=Records) %>%
  arrange(desc(Records)) %>%
  hchart("column", hcaes(x = `Format`, y = Records), name="Records")

```



### Trend

```{r}
test$date_added <- ymd_hms(test$date_added)
test$ym <- as.yearmon(test$date_added) 

trend <- test %>%
  group_by(ym) %>%
  summarise(count = n())

hchart(trend, "line", hcaes(x = as.factor(ym), y = count))

# top years
by_year <- test %>%
  group_by(basic_information.year) %>%
  summarise(Records = n()) %>%
  filter(basic_information.year != 0)

all_dates = seq(min(by_year$basic_information.year), max(by_year$basic_information.year))

by_year_clean = merge(data.frame(date = all_dates),
                            by_year,
                            by.x='date',
                            by.y='basic_information.year',
                            all.x=T,
                            all.y=T)

by_year_clean$Records[is.na(by_year_clean$Records)] = 0

hchart(by_year_clean, "column", hcaes(x = date, y = Records), name="Records")

#cum sum collection
by_mon <- test %>%
  mutate(ym = as.Date(as.yearmon(date_added))) %>%
  group_by(ym) %>%
  summarise(Records = n())

all_dates = seq(as.Date(as.yearmon(min(test$date_added))), as.Date(as.yearmon(max(test$date_added))), by="month")

by_mon_clean = merge(data.frame(date = all_dates),
                            by_mon,
                            by.x='date',
                            by.y='ym',
                            all.x=T,
                            all.y=T)

by_mon_clean$Records[is.na(by_mon_clean$Records)] = 0

by_mon_clean %>%
  mutate(cumsum=cumsum(Records), yearmon = as.yearmon(date)) %>%
  hchart("line", hcaes(x = as.factor(yearmon), y = cumsum), name="Records") %>%
  hc_xAxis(title = list(text = "Month"))

# buying rates per year

data %>%
  group_by(lubridate::year(date_added)) %>%
  summarise(`Average no. of records bought per month`=round(n()/12)) %>%
  hchart("line", hcaes(x = as.factor(`lubridate::year(date_added)`), y = `Average no. of records bought per month`), name="Records") %>%
  hc_xAxis(title = list(text = "Year"))

# buying rates per calendar month
  data %>%
  group_by(lubridate::month(date_added, label=TRUE), lubridate::year(date_added)) %>%
  summarise(`No. of records bought per month`=round(n())) %>%
  group_by(`lubridate::month(date_added, label = ...`) %>%
  summarise(average = sum(`No. of records bought per month`)/n())  
    mutate(sum = sum(`No. of records bought per month`))
  hchart("column", hcaes(x = as.factor(`lubridate::month(date_added, label = ...`), y = `No. of records bought per month`), name="Records") %>%
  hc_xAxis(title = list(text = "Month"))
```


